FORMAT: 1A

# account-rest-api

A generic REST-API for all things user accounts and sessions.

Implements [JSON API](http://jsonapi.org/) according to v1 of the specification.

Send your pull-requests to https://github.com/gr2m/account-rest-api


## Group User

## Session [/session]

The session resource allows users to sign in, sign out and to check their
current session status.

### Sign In [POST]

+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

        {
          data: {
            "attributes": {
              "username": "john@example.com",
              "password": "secret"
            }
          }
        }

+ Response 201 (Content-Type: application/vnd.api+json)

        {
          data: {
            "id": "sessionid123"
          }
        }

+ Response 401 (Content-Type: application/vnd.api+json)

        {
          errors: [{
            "statusCode": "401",
            "error": "Unauthorized",
            "message": "Invalid Credentials"
          }]
        }

### Check session [GET]

+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

+ Response 200 (Content-Type: application/vnd.api+json)

        {
          data: {
            "id": "sessionid123"
          }
        }


### Sign Out [DELETE]

+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

+ Response 204 (Content-Type: application/vnd.api+json)


## Account [/session/account]

The User account resource allows users to sign up, get
or set account properties or destroy their accounts.

Destroying an account, and changing account properties
like username and password, require to pass the user's
password as `x-password` header.

### Sign Up [POST]

+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

        {
          "data": {
            "attributes": {
              "username": "john@example.com",
              "password": "secret",
              "profile": {
                  "customProperty": "foobar"
              }
            }
          }
        }

+ Response 201 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "https://example.com/session/account"
          },
          "data" {
            "id": "abc4567",
            "type": "accounts",
            "attributes": {
              "username": "john@example.com",
              "session": {
                  "id": "sessionid123"
              },
              "profile": {
                  "customProperty": "foobar"
              }
            }
          }
        }

### Fetch [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

+ Response 200 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "https://example.com/session/account"
          },
          "data": {
            "id": "def678",
            "attributes": {
              "username": "jane@example.com",
              "profile": {
                  "fullName": "Jane Doe"
              }
            }
          }            
        }

### Change [PATCH]

+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123
            X-Password: currentsecret

    + Body

            {
              "data": {
                "attributes": {
                  "password": "newsecret"
                }
              }
            }

+ Response 204

### Close [DELETE]

+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123
            X-Password: currentsecret

+ Response 200 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "https://example.com/session/account",
          },
          "data": {
            "id": "abc4567",
            "attributes": {
              "username": "john@example.com",
            },
            "relationships": {
              "profile": {
                "links": {
                  "related": "https://examples.com/session/account/profile"
                },
                "data": {
                  "type": "accountProfile",
                  "customProperty": "foobar"
                }
              }
            }
          }
        }


## Account Profile [/session/account/profile]

All custom user data is stored in the account profile.

### Fetch user account profile [GET]

+ Request (Content-Type: application/vnd.api+json)

    + Headers
            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

+ Response 200 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "https://example.com/session/account/profile"
          },
          "data": {
            "attributes": {
              "fullName": "Jane Doe"
            }
          }
        }

### Update user account profile [PATCH]

+ Request (Content-Type: application/vnd.api+json) 

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

    + Body

            {
              "data": {
                "attributes": {
                  "profile": {
                      "property": "new value"
                  }
                }
              }
            }

+ Response 200 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "https://example.com/session/account/profile"
          },
          "data": {
            "attributes": {
              "profile": {
                  "property": "new value"
              }
            }
          }

## Group Admins

## Accounts [/accounts]

Admins can fetch and manage all user accounts and their profile properties
(including the ones set to `readSecure`)

### Create [POST]

+ Request (Content-Type: application/vnd.api+json)

    + Headers
            Accept: application/vnd.api+json
            
        {
          "data": {
            "attributes": {
              "username": "jane@example.com",
              "password": "secret",
              "profile": {
                  "fullName": "Jane Doe"
              }
            }
          }
        }

+ Response 201 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "https://example.com/accounts/abc4567"
          },
          "data": {
            "id": "abc4567",
            "attributes": {
              "username": "john@example.com",
              "profile": {
                  "fullName": "Jane Doe"
              }
            }
          }
        }


### List all [GET]

+ Request

    + Headers
            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

+ Response 200 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "https://example.com/accounts",
            "first": "https://example.com/accounts",
            "last": "https://example.com/accounts?page=2",
            "next": "https://example.com/accounts?page=2"
          },
          "data": [
              {
                "links": {
                  "self": "https://example.com/accounts/jane@example.com"
                },
                "type": "accounts",
                "id": "def678",
                "attributes": {
                  "username": "jane@example.com",
                  "profile": {
                    "fullName": "Jane Doe",
                    "customProperty": "custom"
                  }
                }
              },
              {
                "links": {
                  "self": "https://example.com/accounts/john@example.com"
                },
                "type": "accounts",
                "id": "abc4567",
                "attributes": {
                  "username": "john@example.com",
                  "profile": {
                    "fullName": "John Example",
                    "customProperty": "foobar"
                  }
                }
              }
          ]
        }

## Account [/accounts/{username}?fields[accounts]={property1,property2}]

+ Parameters
    + username: john@example.com (required, string) - uername of account
    

### Fetch [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

+ Response 200 (Content-Type: application/vnd.api+json)


        {
          "data": {
            "id": "def678",
            "attributes": {
              "username": "jane@example.com",
              "profile": {
                  "fullName": "Jane Doe"
              }
            }
          }
        }

### Change [PATCH]

+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

    + Body

            {
              "data": {
                "attributes": {
                  "profile": {
                      "newProperty": "value",
                      "secureProperty": "wicked"
                  }
                }
              }
            }

+ Response 204


### Delete [DELETE]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

+ Response 200 (Content-Type: application/vnd.api+json)

            {
              "data": {
                "id": "def678",
                "attributes": {
                  "username": "john@example.com"
                }
              }
            }


## requests [/requests]

`GET` is restricted to admins.

### LIST [GET]


+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

+ Response 201 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "http://example.com/requests"
          },
          "data": [
            {
              "links": {
                "self": "http://example.com/requests/1234"
              },
                "id": "1234",
                "type": "passwordreset",
                "attributes": {
                  "contact": "john@example.com",
                  "expires": "2015-07-20T10:00:00-04:00"
                }
            },
          {
            "links": {
              "self": "http://example.com/requests/2345"
            },
            "id": "2345",
            "type": "usernamereminder",
            "attributes": {
              "contact": "jane@example.com",
              "expires": "2015-07-20T15:00:00-04:00"
            }
            }
          ]
        ]

### CREATE [POST]

+ Request (Content-Type: application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json
            
    + Body

            {
              "data": {
                "type": "passwordreset",
                "attributes": {
                  "contact": "john@example.com"
                }
              }
            }

+ Response 201 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "http://example.com/requests/1234"
          },
          "data": {
            "id": "1234",
            "type": "passwordreset",
            "attributes": {
              "contact": "john@example.com",
              "expires": "2015-07-20T15:00:00-04:00"
            }
          }
        }



## Request [/requests/{id}]

`DELETE` is restricted to admins. `GET` makes sense for users to check
for errors that might have occured after creating a request,
like an error during password reset delivery.

+ Parameters
    + id: 1234 (required, string) - request id

### Fetch request by  id [GET]

+ Response 200 (Content-Type: application/vnd.api+json)

        {
          "links": {
            "self": "1234"
          },
          "data": {
            "id": "1234",
            "type": "passwordreset",
            "attributes": {
              "contact": "john@example.com",
              "expires": "2015-07-20T15:00:00-04:00"
            }
          }
        }

### Delete request [DELETE]

+ Response 200 (Content-Type: application/vnd.api+json)

        {
          "data": {
            "id": "1234",
            "type": "passwordreset",
            "attributes": {
              "contact": "john@example.com",
              "expires": "2015-07-20T15:00:00-04:00"
            }
          }
        }
